name:                lefdef
version:             0.2.0.0
github:              "foshardware/lefdef"
license:             BSD3
author:              "Andreas Westerwick"
maintainer:          "westerwick@pconas.de"
copyright:           "2019 Andreas Westerwick"
build-type:          Custom

extra-source-files:
- README.md
- ChangeLog.md

custom-setup:
  dependencies:
  - base >= 4.9 && < 5
  - Cabal
  - process

description:         Please see the README on GitHub at <https://github.com/foshardware/lefdef#readme>

dependencies:
- base >= 4.9 && < 5
- array
- attoparsec
- filepath
- parsec
- scientific
- tasty
- tasty-hunit
- tasty-quickcheck
- text
- vector

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -O2

tests:
  lefdef-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -O2
    - -threaded
    - -rtsopts
    dependencies:
    - lefdef

